version: '3'

services:
  api-db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      POSTGRES_DB: api
    networks:
      - algomart_test
    ports:
      - "5432:5432"
    volumes:
      - api-db:/var/lib/postgresql/data

  cms-db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: cms
      POSTGRES_PASSWORD: cms
      POSTGRES_DB: cms
    networks:
      - algomart_test
    ports:
      - "5433:5432"
    volumes:
      - cms-db:/var/lib/postgresql/data

  cms:
    build:
      context: .
      dockerfile: docker/local/cms/Dockerfile
    restart: always
    depends_on:
      - cms-db
    env_file: apps/cms/.env
    environment:
      # only put values in here that should override the CMS .env file
      DB_CONNECTION_STRING: postgres://cms:cms@cms-db:5432/cms
    networks:
      - algomart_test
    ports:
      - "8055:8055"
    volumes:
      - cms-uploads:/app/uploads

  api:
    build:
      context: .
      dockerfile: docker/local/api/Dockerfile
    restart: always
    depends_on:
      - api-db
      - cms
    env_file: apps/api/.env
    environment:
      # only put values in here that should override the API .env file
      CMS_URL: http://cms:8055
      CMS_PUBLIC_URL: http://localhost:8055
      DATABASE_URL: postgres://api:api@api-db:5432/api
    networks:
      - algomart_test
    ports:
      - "3001:3001"
    volumes:
      - .:/app

  web:
    build:
      context: .
      dockerfile: docker/local/web/Dockerfile
    restart: always
    depends_on:
      - api
      - cms
    env_file: apps/web/.env
    environment:
      # only put values in here that should override the Web .env file
      API_URL: http://api:3001
      IMAGE_DOMAINS: lh3.googleusercontent.com,firebasestorage.googleapis.com,localhost,cms
    networks:
      - algomart_test
    ports:
      - "3000:3000"
    volumes:
      - .:/app

networks:
  algomart_test:

volumes:
  api-db:
  cms-db:
  cms-uploads:
